# Generated by Django 5.2.8 on 2026-07-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_skillgapforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Kubernetes CKA certification'", max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('owner_user_id', models.PositiveBigIntegerField(blank=True, help_text='Auth user id accountable for delivery.', null=True)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, help_text='1-4', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('notes', models.TextField(blank=True)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_actions', to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_actions', to='hr.employeeprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_actions', to='hr.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
