# Generated by Django 5.2.8 on 2026-07-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_trainingaction"),
        ("reviews", "0003_goal_source_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingaction",
            name="goal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="training_actions", to="reviews.goal"),
        ),
    ]
