# Generated by Django 5.2.8 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hr", "0006_trainingaction_goal")]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc_type", models.CharField(choices=[("CONTRACT", "Contract"), ("ID", "Identification"), ("CERTIFICATION", "Certification"), ("POLICY_ACK", "Policy acknowledgement"), ("OTHER", "Other")], max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("reference_url", models.CharField(max_length=500)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("uploaded_by_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hr.employeeprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
