# Generated by Django 5.2.15 on 2026-07-03 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Relative weight in the overall score.'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_user_id', models.PositiveBigIntegerField()),
                ('relationship', models.CharField(choices=[('PEER', 'Peer'), ('REPORT', 'Direct report'), ('OTHER', 'Other')], default='PEER', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedback', to='reviews.performancereview')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('review', 'reviewer_user_id')},
            },
        ),
    ]
