# Generated by Django 5.2.8 on 2026-07-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_reviewtemplate_reviewitem_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="source_review",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spawned_goals", to="reviews.performancereview"),
        ),
    ]
